# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab2.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlab2.proto\"\x13\n\x05\x42otId\x12\n\n\x02Id\x18\x01 \x01(\x05\"\x12\n\x03Map\x12\x0b\n\x03Map\x18\x01 \x01(\t\"\x1c\n\x08\x43ommands\x12\x10\n\x08\x43ommands\x18\x01 \x01(\t\" \n\nMineSerial\x12\x12\n\nMineSerial\x18\x01 \x01(\t\"\x1b\n\x07MinePin\x12\x10\n\x08MinePine\x18\x01 \x01(\t\"\x14\n\x04Test\x12\x0c\n\x04name\x18\x01 \x01(\t2\xa8\x01\n\rGroundControl\x12\x18\n\x06GetMap\x12\x06.BotId\x1a\x04.Map\"\x00\x12\x1d\n\x0bGetCommands\x12\x05.Test\x1a\x05.Test\"\x00\x12\x1f\n\rGetMineSerial\x12\x05.Test\x1a\x05.Test\"\x00\x12\x1d\n\x0bShareFinish\x12\x05.Test\x1a\x05.Test\"\x00\x12\x1e\n\x0cShareMinePin\x12\x05.Test\x1a\x05.Test\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOTID']._serialized_start=14
  _globals['_BOTID']._serialized_end=33
  _globals['_MAP']._serialized_start=35
  _globals['_MAP']._serialized_end=53
  _globals['_COMMANDS']._serialized_start=55
  _globals['_COMMANDS']._serialized_end=83
  _globals['_MINESERIAL']._serialized_start=85
  _globals['_MINESERIAL']._serialized_end=117
  _globals['_MINEPIN']._serialized_start=119
  _globals['_MINEPIN']._serialized_end=146
  _globals['_TEST']._serialized_start=148
  _globals['_TEST']._serialized_end=168
  _globals['_GROUNDCONTROL']._serialized_start=171
  _globals['_GROUNDCONTROL']._serialized_end=339
# @@protoc_insertion_point(module_scope)
