# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab3.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlab3.proto\"\x15\n\x08\x66ilename\x12\t\n\x01\x66\x18\x01 \x01(\t\"5\n\x08MapArray\x12\n\n\x02ma\x18\x01 \x01(\t\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\x05\x12\x0c\n\x04rows\x18\x03 \x01(\x05\"\x13\n\x05\x62otID\x12\n\n\x02\x62i\x18\x01 \x01(\x05\"\x18\n\nmoveString\x12\n\n\x02ms\x18\x01 \x01(\t\"\x16\n\x08mineRand\x12\n\n\x02mr\x18\x01 \x01(\t\"\x1c\n\rmineSerialInt\x12\x0b\n\x03msi\x18\x01 \x01(\x05\"\x13\n\x06notify\x12\t\n\x01n\x18\x01 \x01(\t\"\x19\n\x0c\x63onfirmation\x12\t\n\x01\x63\x18\x01 \x01(\t21\n\rgroundControl\x12 \n\x06getMap\x12\t.filename\x1a\t.MapArray\"\x00\x32\x35\n\x0e\x43ommandService\x12#\n\ngetCommand\x12\x06.botID\x1a\x0b.moveString\"\x00\x32\x41\n\x11MineSerialService\x12,\n\rgetMineSerial\x12\t.mineRand\x1a\x0e.mineSerialInt\"\x00\x32J\n\x1e\x44\x65\x66usedMineNotificationService\x12(\n\x0cincomingNoti\x12\x07.notify\x1a\r.confirmation\"\x00\x42\x32\n\x1dio.grpc.examples.myhelloworldB\tLab2ProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab3_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035io.grpc.examples.myhelloworldB\tLab2ProtoP\001\242\002\003HLW'
  _globals['_FILENAME']._serialized_start=14
  _globals['_FILENAME']._serialized_end=35
  _globals['_MAPARRAY']._serialized_start=37
  _globals['_MAPARRAY']._serialized_end=90
  _globals['_BOTID']._serialized_start=92
  _globals['_BOTID']._serialized_end=111
  _globals['_MOVESTRING']._serialized_start=113
  _globals['_MOVESTRING']._serialized_end=137
  _globals['_MINERAND']._serialized_start=139
  _globals['_MINERAND']._serialized_end=161
  _globals['_MINESERIALINT']._serialized_start=163
  _globals['_MINESERIALINT']._serialized_end=191
  _globals['_NOTIFY']._serialized_start=193
  _globals['_NOTIFY']._serialized_end=212
  _globals['_CONFIRMATION']._serialized_start=214
  _globals['_CONFIRMATION']._serialized_end=239
  _globals['_GROUNDCONTROL']._serialized_start=241
  _globals['_GROUNDCONTROL']._serialized_end=290
  _globals['_COMMANDSERVICE']._serialized_start=292
  _globals['_COMMANDSERVICE']._serialized_end=345
  _globals['_MINESERIALSERVICE']._serialized_start=347
  _globals['_MINESERIALSERVICE']._serialized_end=412
  _globals['_DEFUSEDMINENOTIFICATIONSERVICE']._serialized_start=414
  _globals['_DEFUSEDMINENOTIFICATIONSERVICE']._serialized_end=488
# @@protoc_insertion_point(module_scope)
